services:
  devops-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: devops-mcp:latest
    container_name: devops-mcp-server
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - MCP__Protocol=http
      - MCP__ENDPOINT=/mcp
      - MCP__ENABLE_CORS=true
      - AzureDevOps__OrganizationUrl=${AZURE_DEVOPS_ORG_URL}
      - AzureDevOps__PersonalAccessToken=${AZURE_DEVOPS_PAT}
      - AzureDevOps__AuthMethod=PersonalAccessToken
      - Logging__LogLevel__Default=Information
    volumes:
      - ./logs:/app/logs