apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-mcp

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: devops-mcp
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize