apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-mcp
  namespace: devops-mcp
  labels:
    app.kubernetes.io/name: devops-mcp
    app.kubernetes.io/component: server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-mcp
  namespace: devops-mcp
  labels:
    app.kubernetes.io/name: devops-mcp
    app.kubernetes.io/component: server
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-mcp
  namespace: devops-mcp
  labels:
    app.kubernetes.io/name: devops-mcp
    app.kubernetes.io/component: server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devops-mcp
subjects:
- kind: ServiceAccount
  name: devops-mcp
  namespace: devops-mcp